name: CI

on:
  repository_dispatch:

jobs:

  openapi:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17.9.1

      - name: Get npm cache directory
        id: npm-cache-directory
        run: |
          echo "::set-output name=directory::$(npm config get cache)"

      - name: Cache npm
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-directory.outputs.directory }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys:
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run openapi
